[book]
authors = ["Keepin' Tracks"]
language = "en"
multilingual = false
src = "src"
title = "Keepin' Tracks Documentation"

[output.html.fold]
enable = true

[output.html]
git-repository-url = "https://keepintracks.com"
git-repository-icon = "fa-home"